export enum ApiRoutes {
  LOGIN = 'login',
  DASHBOARD = 'dashboard',
  DEPARTEMENTS = 'departements',
  COMMUNES = 'communes',
  ARRONDISSEMENTS = 'arrondissements',
  QUARTIERS_VILLAGES = 'quartiers-villages',
  GUPS = 'gups  ',
  CENTRE_SANTE = 'centre-sante',
  METIERS = 'Metiers  ',
  TYPES_HANDICAPS = 'types-handicaps',
  TAUX_HANDICAPS = 'taux-handicaps',
  TYPES_KITS = 'types-kits',
  TYPES_SOINS = 'types-soins',
  PROFESSIONS = 'professions',
  UTILISATEURS = 'utilisateurs',
  SESSIONS = 'sessions',
  DEMANDEURS = 'demandeurs',
  CARTES = 'cartes',
  ETUDIANTSHANDS = 'etudiantshands',
  DEMANDESCRE = 'demandescre',
  DEMANDESINS = 'demandesins',
  DOSSIERNAIS = 'dossiernais',
  
  ETABLISSEMENTS = 'etablissements',
  RENDEZVOUS = 'rendezvous',
  AIDES = 'aides',
  PROFILE = 'profile',
}