export enum Paths {
  // Route STAFF
  LOGIN = 'login',
  FORGOT_PASSWORD = 'staff/forgot-password',
  VERIFY_CODE = 'staff/verify-code',
  RESET_PASSWORD = 'staff/reset-password',

  DASHBOARD = 'staff/dashboard',

  // Route PARAMETRES
  COMMUNES = 'staff/parametres/communes',
  DEPARTEMENTS = 'staff/parametres/departements',
  ARRONDISSEMENTS = 'staff/parametres/arrondissements',
  QUARTIERS_VILLAGES = 'staff/parametres/quartiers-villages',
  GUPS = 'staff/parametres/gups',
  CENTRE_SANTE = 'staff/parametres/centre-sante',
  METIERS = 'staff/parametres/metiers',
  TYPES_HANDICAPS = 'staff/parametres/types-handicaps',
  TAUX_HANDICAPS = 'staff/parametres/taux-handicaps',
  TYPES_KITS = 'staff/parametres/types-kits',
  TYPES_SOINS = 'staff/parametres/types-soins',
  PROFESSIONS = 'staff/parametres/professions',
  UTILISATEURS = 'staff/parametres/utilisateurs',
  SESSIONS = 'staff/parametres/sessions',
DEMANDEURS = 'staff/base/demandeurs',
DEMANDEURS_SESSION = 'staff/session-active/demandeurs',
  CARTES = 'staff/base/cartes',
  CARTES_SESSION = 'staff/session-active/cartes',
ETUDIANTSHANDS = 'staff/base/etudiantshands',
ETUDIANTSHANDS_SESSION = 'staff/session-active/etudiantshands',
DEMANDESCRE = 'staff/base/demandescre',
DEMANDESCRE_SESSION = 'staff/session-active/demandescre',
DEMANDESINS = 'staff/base/demandesins',
DEMANDESINS_SESSION = 'staff/session-active/demandesins',
  DOSSIERNAIS = 'staff/base/dossiernais',
  DOSSIERNAIS_SESSION = 'staff/session-active/dossiernais',
ETABLISSEMENTS = 'staff/base/etablissements',
ETABLISSEMENTS_SESSION = 'staff/session-active/etablissements',
RENDEZVOUS = 'staff/base/rendezvous',
RENDEZVOUS_SESSION = 'staff/session-active/rendezvous',
AIDES = 'staff/base/aides',
AIDES_SESSION = 'staff/session-active/aides',
  PROFILE = 'staff/profile',
}